### PR TITLE
Small Fixes

### PR DESCRIPTION
**Pull request by oa495**
addresses issue #8 #7 (empty RSVP fields in intranet should auto link to http://rsvp.techatnyu.org/ &  parse short descriptions and http:// strings automatically link)
 hacky fix to sort events by upcoming and past #5

### CODE REVIEW

**Comment by oa495** [comment]
@grungerabbit can u take a look at this?

**Comment by grungerabbit** [comment]
you the best. couple of notes

1. the `past | upcoming` thing should show up on the current month only - maybe it should switch to just `past` on prior months and `upcoming` on future months (also i would switch the order to be literally `past | upcoming`, to match the `previous` and `next` affordances
2. it should also tell you which state is selected with an active style. maybe a simple bottom border? or color change?
3. is the green just a temp styling? we should sit down and properly assign colors for event types. @ethanresnick had worked on something last year about this.
4. #7 and #8 are great, thanks for closing those out

i can merge this and we can think about 1-3? lmk

**Comment by oa495** [comment]
1. will do.
2. there is an active style. there's a border that appears under the event when a day is clicked.
3. green is temporary. do we need to assign colors for event types? I feel like it doesn't matter. You see an event you like you go to the facebook page.

**Comment by grungerabbit** [comment]
2. i mean the active state on the `past | upcoming` control lol - it's not really important since you know which you literally clicked on, but it's nice to remind people

**Comment by grungerabbit** [comment]
and yeah, the colors per event type doesn't necessarily matter, but it might be nice to filter someday like we did for SW

screenshot 2015-11-09 21 21 27

**Comment by grungerabbit** [comment]
again these are all "might be nice"s

i'll merge rn

**Comment by grungerabbit** [comment]
yeah so close out these small nitpicks and do another PR

**Pull request merged**
